-- MySQL Script generated by MySQL Workbench
-- Wed Jul 29 11:07:56 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Address` (
  `AdressID` INT NOT NULL AUTO_INCREMENT,
  `Street` VARCHAR(80) NULL,
  `StreetNumber` VARCHAR(10) NULL,
  `Floor` VARCHAR(10) NULL,
  `Door` VARCHAR(10) NULL,
  `City` VARCHAR(80) NULL,
  `PostalCode` VARCHAR(10) NULL,
  `Country` VARCHAR(80) NULL,
  PRIMARY KEY (`AdressID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Supplier` (
  `SupplierID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(80) NULL,
  `Phone` VARCHAR(20) NULL,
  `Fax` VARCHAR(20) NULL,
  `NIF` VARCHAR(20) NULL,
  `Address_idAdress` INT NOT NULL,
  PRIMARY KEY (`SupplierID`),
  INDEX `fk_Supplier_Address1_idx` (`Address_idAdress` ASC) VISIBLE,
  CONSTRAINT `fk_Supplier_Address1`
    FOREIGN KEY (`Address_idAdress`)
    REFERENCES `mydb`.`Address` (`AdressID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Brand` (
  `BrandID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(80) NULL,
  `Supplier_idSupplier` INT NOT NULL,
  PRIMARY KEY (`BrandID`),
  INDEX `fk_Brand_Supplier_idx` (`Supplier_idSupplier` ASC) VISIBLE,
  CONSTRAINT `fk_Brand_Supplier`
    FOREIGN KEY (`Supplier_idSupplier`)
    REFERENCES `mydb`.`Supplier` (`SupplierID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `EmployeeID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`EmployeeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `ClientID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(80) NULL,
  `Phone` VARCHAR(20) NULL,
  `Email` VARCHAR(80) NULL,
  `registrationDate` DATE NULL,
  `Address_idAdress` INT NOT NULL,
  `referredBy` INT NOT NULL,
  PRIMARY KEY (`ClientID`),
  INDEX `fk_Client_Address1_idx` (`Address_idAdress` ASC) VISIBLE,
  INDEX `fk_Client_Client1_idx` (`referredBy` ASC) VISIBLE,
  CONSTRAINT `fk_Client_Address1`
    FOREIGN KEY (`Address_idAdress`)
    REFERENCES `mydb`.`Address` (`AdressID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_Client1`
    FOREIGN KEY (`referredBy`)
    REFERENCES `mydb`.`Client` (`ClientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sale` (
  `SaleID` INT NOT NULL AUTO_INCREMENT,
  `saleDate` DATE NULL,
  `Employee_idEmployee` INT NOT NULL,
  `Client_idClient` INT NOT NULL,
  PRIMARY KEY (`SaleID`),
  INDEX `fk_Sale_Employee1_idx` (`Employee_idEmployee` ASC) VISIBLE,
  INDEX `fk_Sale_Client1_idx` (`Client_idClient` ASC) VISIBLE,
  CONSTRAINT `fk_Sale_Employee1`
    FOREIGN KEY (`Employee_idEmployee`)
    REFERENCES `mydb`.`Employee` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sale_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `mydb`.`Client` (`ClientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Glasses` (
  `GlassesID` INT NOT NULL,
  `LeftPrescription` DECIMAL(5,2) NULL,
  `RightPrescription` DECIMAL(5,2) NULL,
  `FrameType` ENUM('floating', 'plastic', 'metal') NULL,
  `Price` DECIMAL(10,2) NULL,
  `RightGlassColor` VARCHAR(45) NULL,
  `leftGlassColor` VARCHAR(45) NULL,
  `FrameColor` VARCHAR(45) NULL,
  `Brand_idBrand` INT NOT NULL,
  `Sale_idSale` INT NOT NULL,
  PRIMARY KEY (`GlassesID`),
  INDEX `fk_Glasses_Brand1_idx` (`Brand_idBrand` ASC) VISIBLE,
  INDEX `fk_Glasses_Sale1_idx` (`Sale_idSale` ASC) VISIBLE,
  CONSTRAINT `fk_Glasses_Brand1`
    FOREIGN KEY (`Brand_idBrand`)
    REFERENCES `mydb`.`Brand` (`BrandID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Glasses_Sale1`
    FOREIGN KEY (`Sale_idSale`)
    REFERENCES `mydb`.`Sale` (`SaleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
