-- MySQL Script generated by MySQL Workbench
-- Wed Jul 29 13:30:00 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Client` (
  `ClientID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Surname` VARCHAR(45) NULL,
  `Address` VARCHAR(100) NULL,
  `PostalCode` VARCHAR(10) NULL,
  `City` VARCHAR(45) NULL,
  `Region` VARCHAR(45) NULL,
  `Phone` VARCHAR(20) NULL,
  PRIMARY KEY (`ClientID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`Shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Shop` (
  `ShopID` INT NOT NULL AUTO_INCREMENT,
  `Address` VARCHAR(45) NULL,
  `PostalCode` VARCHAR(10) NULL,
  `City` VARCHAR(45) NULL,
  `Region` VARCHAR(45) NULL,
  PRIMARY KEY (`ShopID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Order` (
  `CommandID` INT NOT NULL AUTO_INCREMENT,
  `DateTime` DATETIME NULL,
  `OrderType` ENUM("pickup", "delivery") NULL,
  `TotalPrice` DECIMAL(10,2) NULL,
  `Client_ClientID` INT NOT NULL,
  `Shop_ShopID` INT NOT NULL,
  PRIMARY KEY (`CommandID`),
  INDEX `fk_Command_Client_idx` (`Client_ClientID` ASC) VISIBLE,
  INDEX `fk_Command_Shop1_idx` (`Shop_ShopID` ASC) VISIBLE,
  CONSTRAINT `fk_Command_Client`
    FOREIGN KEY (`Client_ClientID`)
    REFERENCES `pizzeria`.`Client` (`ClientID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Command_Shop1`
    FOREIGN KEY (`Shop_ShopID`)
    REFERENCES `pizzeria`.`Shop` (`ShopID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Category` (
  `CategoryID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`CategoryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Product` (
  `ProductID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `ProductType` ENUM("pizza", "hamburguer", "drinks") NULL,
  `Image` BLOB NULL,
  `Price` DECIMAL(5,2) NULL,
  `Description` TEXT NULL,
  `Category_CategoryID` INT NULL,
  PRIMARY KEY (`ProductID`),
  INDEX `fk_Product_Category1_idx` (`Category_CategoryID` ASC) VISIBLE,
  CONSTRAINT `fk_Product_Category1`
    FOREIGN KEY (`Category_CategoryID`)
    REFERENCES `pizzeria`.`Category` (`CategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Employee` (
  `EmployeeID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Surname` VARCHAR(45) NULL,
  `NIF` VARCHAR(20) NULL,
  `Phone` VARCHAR(20) NULL,
  `Role` ENUM("driver", "cook") NULL,
  `Shop_ShopID` INT NOT NULL,
  PRIMARY KEY (`EmployeeID`),
  INDEX `fk_Employee_Shop1_idx` (`Shop_ShopID` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_Shop1`
    FOREIGN KEY (`Shop_ShopID`)
    REFERENCES `pizzeria`.`Shop` (`ShopID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`Deliver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Deliver` (
  `DeliverID` INT NOT NULL AUTO_INCREMENT,
  `DeliverDateTime` DATETIME NULL,
  `Command_CommandID` INT NOT NULL,
  `Employee_EmployeeID` INT NOT NULL,
  PRIMARY KEY (`DeliverID`),
  INDEX `fk_Delivers_Command1_idx` (`Command_CommandID` ASC) VISIBLE,
  INDEX `fk_Delivers_Employee1_idx` (`Employee_EmployeeID` ASC) VISIBLE,
  CONSTRAINT `fk_Delivers_Command1`
    FOREIGN KEY (`Command_CommandID`)
    REFERENCES `pizzeria`.`Order` (`CommandID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Delivers_Employee1`
    FOREIGN KEY (`Employee_EmployeeID`)
    REFERENCES `pizzeria`.`Employee` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`Order_has_Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Order_has_Product` (
  `Command_CommandID` INT NOT NULL,
  `Product_ProductID` INT NOT NULL,
  `Quantity` INT NULL,
  PRIMARY KEY (`Command_CommandID`, `Product_ProductID`),
  INDEX `fk_Command_has_Product_Product1_idx` (`Product_ProductID` ASC) VISIBLE,
  INDEX `fk_Command_has_Product_Command1_idx` (`Command_CommandID` ASC) VISIBLE,
  CONSTRAINT `fk_Command_has_Product_Command1`
    FOREIGN KEY (`Command_CommandID`)
    REFERENCES `pizzeria`.`Order` (`CommandID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Command_has_Product_Product1`
    FOREIGN KEY (`Product_ProductID`)
    REFERENCES `pizzeria`.`Product` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


